/** App-wide constants & default settings */

export const STORAGE_KEYS = {
  settings: "ttt.settings.v1",
  progress: "ttt.progress.v1",
  history: "ttt.history.v1",
  ui: "ttt.ui.v1",
  keyStats: "ttt.keyStats.v1",
  achievements: "ttt.achievements.v1",
};

export const DEFAULT_SETTINGS = {
  theme: "dark",
  fontSize: "medium", // small | medium | large
  fontFa: "vazirmatn",
  fontEn: "system",
  soundEnabled: true,
  soundVolume: 0.55,
  keySound: true,
  errorSound: true,
  completeSound: true,
  caseSensitive: true,
  includeNumbers: true,
  includePunctuation: true,
  practiceLength: "medium",
  practiceDuration: 60,
  practiceSource: "sentences",
  showKeyboard: true,
  showFingerHint: true,
  showFingerIcon: true,
  showHandsDiagram: true,
  strictMode: true,
  smoothCursor: true,
  dailyGoal: 3,
};

export const THEMES = ["dark", "light", "sand", "sky", "forest", "indigo"];

export const FONTS_FA = [
  { id: "vazirmatn", label: "وزیرمتن", stack: '"Vazirmatn", "Segoe UI", Tahoma, sans-serif' },
  { id: "noto-naskh", label: "نسخ نوتیو", stack: '"Noto Naskh Arabic", "Vazirmatn", serif' },
  { id: "noto-kufi", label: "کوفی نوتیو", stack: '"Noto Kufi Arabic", "Vazirmatn", sans-serif' },
  { id: "amiri", label: "امیری (کلاسیک)", stack: '"Amiri", "Vazirmatn", serif' },
  { id: "baloo", label: "بالو (گرد)", stack: '"Baloo Bhaijaan 2", "Vazirmatn", sans-serif' },
  { id: "lalezar", label: "لاله‌زار (دکوراتیو)", stack: '"Lalezar", "Vazirmatn", sans-serif' },
  { id: "markazi", label: "مرکزی (روزنامه‌ای)", stack: '"Markazi Text", "Vazirmatn", serif' },
];

export const FONTS_EN = [
  { id: "system", label: "System", stack: '"Segoe UI", system-ui, -apple-system, sans-serif' },
  { id: "inter", label: "Inter", stack: '"Inter", "Segoe UI", system-ui, sans-serif' },
  { id: "roboto", label: "Roboto", stack: '"Roboto", "Segoe UI", sans-serif' },
  { id: "georgia", label: "Georgia", stack: 'Georgia, "Times New Roman", serif' },
  { id: "mono", label: "Monospace", stack: '"Cascadia Code", Consolas, monospace' },
];

export const UI_STRINGS = {
  fa: {
    appName: "مربی تایپ",
    home: "خانه",
    curriculum: "مسیر آموزشی",
    practice: "تمرین آزاد",
    stats: "پیشرفت من",
    settings: "تنظیمات",
    start: "شروع",
    continue: "ادامه",
    retry: "تکرار",
    next: "مرحله بعد",
    back: "بازگشت",
    exit: "خروج از جلسه",
    complete: "تکمیل شد",
    locked: "قفل",
    available: "در دسترس",
    done: "انجام شد",
    wpm: "WPM",
    cpm: "CPM",
    accuracy: "دقت",
    time: "زمان",
    errors: "خطا",
    score: "امتیاز",
    speed: "سرعت",
    correct: "درست",
    wrong: "اشتباه",
    corrected: "اصلاح‌شده",
    remaining: "باقی‌مانده",
    pass: "قبول",
    fail: "نیاز به تمرین بیشتر",
    nextKey: "کلید بعدی",
    finger: "انگشت",
    leftHand: "دست چپ",
    rightHand: "دست راست",
    startTyping: "برای شروع تایپ کنید…",
    noHistory: "هنوز جلسه‌ای ثبت نشده است. اولین تمرین را شروع کنید!",
    resetTitle: "بازنشانی و حذف داده‌ها",
    resetBody: "آمار، مراحل، دستاوردها و تاریخچه جلسات حذف می‌شود. تنظیمات (تم، صدا) باقی می‌ماند.",
    resetConfirm: "حذف پیشرفت",
    wipeAll: "حذف کامل همه‌چیز (شامل تنظیمات)",
    wipeBody: "همه داده‌ها از جمله تنظیمات حذف و برنامه به حالت اولیه برمی‌گردد.",
    cancel: "انصراف",
    saved: "ذخیره شد",
    level: "سطح",
    easy: "آسان",
    medium: "متوسط",
    hard: "پیشرفته",
    length: "طول متن",
    short: "کوتاه",
    long: "بلند",
    duration: "مدت زمان",
    unlimited: "بدون محدودیت",
    minute: "دقیقه",
    language: "زبان مسیر",
    theme: "تم ظاهری",
    sound: "صدا",
    volume: "بلندی صدا",
    showKeyboard: "نمایش صفحه‌کلید مجازی",
    fingerHint: "راهنمای انگشت",
    showFingerIcon: "نمایش شکل انگشت روی کلید هدف",
    strictMode: "حالت سخت‌گیرانه (حرف درست الزامی)",
    caseSensitive: "حساس به بزرگی/کوچکی",
    numbers: "اعداد",
    punctuation: "علائم نگارشی",
    fontSize: "اندازه فونت",
    typeSource: "نوع محتوا",
    words: "کلمات",
    sentences: "جملات",
    randomChars: "حروف تصادفی",
    stars: "ستاره",
    goal: "هدف مرحله",
    minSpeed: "حداقل سرعت",
    minAcc: "حداقل دقت",
    sessionDone: "جلسه تمام شد",
    newRecord: "رکورد جدید!",
    tryAgain: "دوباره امتحان کن",
    goToNext: "رفتن به مرحله بعدی",
    practiceAgain: "تمرین مجدد",
    freePractice: "تمرین آزاد",
    selectPath: "یک مسیر آموزشی را انتخاب کنید",
    faTrack: "فارسی",
    enTrack: "English",
    progressFa: "پیشرفت فارسی",
    progressEn: "پیشرفت انگلیسی",
    sessions: "جلسات",
    bestWpm: "بهترین سرعت",
    avgAcc: "میانگین دقت",
    totalTime: "کل زمان تمرین",
    recentSessions: "جلسات اخیر",
    chartWpm: "نمودار سرعت",
    chartAcc: "نمودار دقت",
    openLesson: "شروع مرحله",
    introTitle: "جایگاه دست‌ها",
    keepGoing: "ادامه بده!",
    almost: "تقریباً آماده‌ای",
    needWork: "هنوز به حد نصاب نرسیدی",
  },
  en: {
    appName: "Touch Typing",
    home: "Home",
    curriculum: "Curriculum",
    practice: "Free Practice",
    stats: "My Progress",
    settings: "Settings",
    start: "Start",
    continue: "Continue",
    retry: "Retry",
    next: "Next stage",
    back: "Back",
    exit: "Exit session",
    complete: "Completed",
    locked: "Locked",
    available: "Available",
    done: "Done",
    wpm: "WPM",
    cpm: "CPM",
    accuracy: "Accuracy",
    time: "Time",
    errors: "Errors",
    score: "Score",
    speed: "Speed",
    correct: "Correct",
    wrong: "Wrong",
    corrected: "Corrected",
    remaining: "Remaining",
    pass: "Passed",
    fail: "Keep practicing",
    nextKey: "Next key",
    finger: "Finger",
    leftHand: "Left hand",
    rightHand: "Right hand",
    startTyping: "Start typing to begin…",
    noHistory: "No sessions yet. Start your first practice!",
    resetTitle: "Reset & delete data",
    resetBody: "Stats, stages, achievements and session history will be deleted. Settings (theme, sound) stay.",
    resetConfirm: "Reset progress",
    wipeAll: "Wipe everything (including settings)",
    wipeBody: "All data including settings will be deleted and the app returns to defaults.",
    cancel: "Cancel",
    saved: "Saved",
    level: "Level",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    length: "Text length",
    short: "Short",
    long: "Long",
    duration: "Duration",
    unlimited: "Unlimited",
    minute: "min",
    language: "Track language",
    theme: "Theme",
    sound: "Sound",
    volume: "Volume",
    showKeyboard: "Show virtual keyboard",
    fingerHint: "Finger hint",
    showFingerIcon: "Show finger shape on target key",
    strictMode: "Strict mode (correct key required)",
    caseSensitive: "Case sensitive",
    numbers: "Numbers",
    punctuation: "Punctuation",
    fontSize: "Font size",
    typeSource: "Content type",
    words: "Words",
    sentences: "Sentences",
    randomChars: "Random chars",
    stars: "Stars",
    goal: "Stage goal",
    minSpeed: "Min speed",
    minAcc: "Min accuracy",
    sessionDone: "Session complete",
    newRecord: "New record!",
    tryAgain: "Try again",
    goToNext: "Go to next stage",
    practiceAgain: "Practice again",
    freePractice: "Free practice",
    selectPath: "Choose a learning path",
    faTrack: "فارسی",
    enTrack: "English",
    progressFa: "Persian progress",
    progressEn: "English progress",
    sessions: "Sessions",
    bestWpm: "Best WPM",
    avgAcc: "Avg accuracy",
    totalTime: "Total practice",
    recentSessions: "Recent sessions",
    chartWpm: "Speed chart",
    chartAcc: "Accuracy chart",
    openLesson: "Start stage",
    introTitle: "Hand position",
    keepGoing: "Keep going!",
    almost: "Almost ready",
    needWork: "Not quite there yet",
  },
};

export function t(lang, key) {
  return UI_STRINGS[lang]?.[key] ?? UI_STRINGS.en[key] ?? key;
}
